<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * AllCountriesSeeder
 *
 * Seeds all ~195 UN-recognised countries with ISO 3166-1 alpha-2 codes,
 * English/Spanish names, flag emojis, and approximate centre coordinates.
 *
 * Uses firstOrCreate so it is safe to run on an existing database.
 * Must run BEFORE GeographySeeder / WorldGeographySeeder so every country
 * row exists before regions and cities reference it.
 */
class AllCountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['code' => 'AD', 'name' => 'Andorra',                          'name_es' => 'Andorra',                           'lat' =>  42.5063, 'lon' =>    1.5218, 'zoom' => 10],
            ['code' => 'AE', 'name' => 'United Arab Emirates',             'name_es' => 'Emiratos Árabes Unidos',             'lat' =>  23.4241, 'lon' =>   53.8478, 'zoom' =>  6],
            ['code' => 'AF', 'name' => 'Afghanistan',                      'name_es' => 'Afganistán',                        'lat' =>  33.9391, 'lon' =>   67.7100, 'zoom' =>  5],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda',              'name_es' => 'Antigua y Barbuda',                  'lat' =>  17.0608, 'lon' =>  -61.7964, 'zoom' => 10],
            ['code' => 'AL', 'name' => 'Albania',                          'name_es' => 'Albania',                           'lat' =>  41.1533, 'lon' =>   20.1683, 'zoom' =>  7],
            ['code' => 'AM', 'name' => 'Armenia',                          'name_es' => 'Armenia',                           'lat' =>  40.0691, 'lon' =>   45.0382, 'zoom' =>  7],
            ['code' => 'AO', 'name' => 'Angola',                           'name_es' => 'Angola',                            'lat' => -11.2027, 'lon' =>   17.8739, 'zoom' =>  5],
            ['code' => 'AR', 'name' => 'Argentina',                        'name_es' => 'Argentina',                         'lat' => -38.4161, 'lon' =>  -63.6167, 'zoom' =>  4],
            ['code' => 'AT', 'name' => 'Austria',                          'name_es' => 'Austria',                           'lat' =>  47.5162, 'lon' =>   14.5501, 'zoom' =>  6],
            ['code' => 'AU', 'name' => 'Australia',                        'name_es' => 'Australia',                         'lat' => -25.2744, 'lon' =>  133.7751, 'zoom' =>  4],
            ['code' => 'AZ', 'name' => 'Azerbaijan',                       'name_es' => 'Azerbaiyán',                        'lat' =>  40.1431, 'lon' =>   47.5769, 'zoom' =>  7],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina',           'name_es' => 'Bosnia y Herzegovina',               'lat' =>  43.9159, 'lon' =>   17.6791, 'zoom' =>  7],
            ['code' => 'BB', 'name' => 'Barbados',                         'name_es' => 'Barbados',                          'lat' =>  13.1939, 'lon' =>  -59.5432, 'zoom' => 11],
            ['code' => 'BD', 'name' => 'Bangladesh',                       'name_es' => 'Bangladés',                         'lat' =>  23.6850, 'lon' =>   90.3563, 'zoom' =>  6],
            ['code' => 'BE', 'name' => 'Belgium',                          'name_es' => 'Bélgica',                           'lat' =>  50.5039, 'lon' =>    4.4699, 'zoom' =>  7],
            ['code' => 'BF', 'name' => 'Burkina Faso',                     'name_es' => 'Burkina Faso',                      'lat' =>  12.3640, 'lon' =>   -1.5275, 'zoom' =>  6],
            ['code' => 'BG', 'name' => 'Bulgaria',                         'name_es' => 'Bulgaria',                          'lat' =>  42.7339, 'lon' =>   25.4858, 'zoom' =>  7],
            ['code' => 'BH', 'name' => 'Bahrain',                          'name_es' => 'Baréin',                            'lat' =>  26.0275, 'lon' =>   50.5500, 'zoom' =>  9],
            ['code' => 'BI', 'name' => 'Burundi',                          'name_es' => 'Burundi',                           'lat' =>  -3.3731, 'lon' =>   29.9189, 'zoom' =>  8],
            ['code' => 'BJ', 'name' => 'Benin',                            'name_es' => 'Benín',                             'lat' =>   9.3077, 'lon' =>    2.3158, 'zoom' =>  7],
            ['code' => 'BN', 'name' => 'Brunei',                           'name_es' => 'Brunéi',                            'lat' =>   4.5353, 'lon' =>  114.7277, 'zoom' =>  9],
            ['code' => 'BO', 'name' => 'Bolivia',                          'name_es' => 'Bolivia',                           'lat' => -16.2902, 'lon' =>  -63.5887, 'zoom' =>  5],
            ['code' => 'BR', 'name' => 'Brazil',                           'name_es' => 'Brasil',                            'lat' => -14.2350, 'lon' =>  -51.9253, 'zoom' =>  4],
            ['code' => 'BS', 'name' => 'Bahamas',                          'name_es' => 'Bahamas',                           'lat' =>  25.0343, 'lon' =>  -77.3963, 'zoom' =>  7],
            ['code' => 'BT', 'name' => 'Bhutan',                          'name_es' => 'Bután',                              'lat' =>  27.5142, 'lon' =>   90.4336, 'zoom' =>  8],
            ['code' => 'BW', 'name' => 'Botswana',                         'name_es' => 'Botsuana',                          'lat' => -22.3285, 'lon' =>   24.6849, 'zoom' =>  6],
            ['code' => 'BY', 'name' => 'Belarus',                          'name_es' => 'Bielorrusia',                       'lat' =>  53.7098, 'lon' =>   27.9534, 'zoom' =>  6],
            ['code' => 'BZ', 'name' => 'Belize',                           'name_es' => 'Belice',                            'lat' =>  17.1899, 'lon' =>  -88.4976, 'zoom' =>  7],
            ['code' => 'CA', 'name' => 'Canada',                           'name_es' => 'Canadá',                            'lat' =>  56.1304, 'lon' => -106.3468, 'zoom' =>  3],
            ['code' => 'CD', 'name' => 'DR Congo',                         'name_es' => 'República Democrática del Congo',   'lat' =>  -4.0383, 'lon' =>   21.7587, 'zoom' =>  5],
            ['code' => 'CF', 'name' => 'Central African Republic',         'name_es' => 'República Centroafricana',           'lat' =>   6.6111, 'lon' =>   20.9394, 'zoom' =>  6],
            ['code' => 'CG', 'name' => 'Republic of the Congo',            'name_es' => 'República del Congo',               'lat' =>  -0.2280, 'lon' =>   15.8277, 'zoom' =>  6],
            ['code' => 'CH', 'name' => 'Switzerland',                      'name_es' => 'Suiza',                             'lat' =>  46.8182, 'lon' =>    8.2275, 'zoom' =>  7],
            ['code' => 'CI', 'name' => "Côte d'Ivoire",                   'name_es' => 'Costa de Marfil',                   'lat' =>   7.5400, 'lon' =>   -5.5471, 'zoom' =>  6],
            ['code' => 'CL', 'name' => 'Chile',                            'name_es' => 'Chile',                             'lat' => -35.6751, 'lon' =>  -71.5430, 'zoom' =>  4],
            ['code' => 'CM', 'name' => 'Cameroon',                         'name_es' => 'Camerún',                           'lat' =>   7.3697, 'lon' =>   12.3547, 'zoom' =>  6],
            ['code' => 'CN', 'name' => 'China',                            'name_es' => 'China',                             'lat' =>  35.8617, 'lon' =>  104.1954, 'zoom' =>  4],
            ['code' => 'CO', 'name' => 'Colombia',                         'name_es' => 'Colombia',                          'lat' =>   4.5709, 'lon' =>  -74.2973, 'zoom' =>  5],
            ['code' => 'CR', 'name' => 'Costa Rica',                       'name_es' => 'Costa Rica',                        'lat' =>   9.7489, 'lon' =>  -83.7534, 'zoom' =>  7],
            ['code' => 'CU', 'name' => 'Cuba',                             'name_es' => 'Cuba',                              'lat' =>  21.5218, 'lon' =>  -77.7812, 'zoom' =>  6],
            ['code' => 'CV', 'name' => 'Cape Verde',                       'name_es' => 'Cabo Verde',                        'lat' =>  16.5388, 'lon' =>  -23.0418, 'zoom' =>  8],
            ['code' => 'CY', 'name' => 'Cyprus',                           'name_es' => 'Chipre',                            'lat' =>  35.1264, 'lon' =>   33.4299, 'zoom' =>  8],
            ['code' => 'CZ', 'name' => 'Czech Republic',                   'name_es' => 'República Checa',                   'lat' =>  49.8175, 'lon' =>   15.4730, 'zoom' =>  7],
            ['code' => 'DE', 'name' => 'Germany',                          'name_es' => 'Alemania',                          'lat' =>  51.1657, 'lon' =>   10.4515, 'zoom' =>  5],
            ['code' => 'DJ', 'name' => 'Djibouti',                         'name_es' => 'Yibuti',                            'lat' =>  11.8251, 'lon' =>   42.5903, 'zoom' =>  8],
            ['code' => 'DK', 'name' => 'Denmark',                          'name_es' => 'Dinamarca',                         'lat' =>  56.2639, 'lon' =>    9.5018, 'zoom' =>  6],
            ['code' => 'DM', 'name' => 'Dominica',                         'name_es' => 'Dominica',                          'lat' =>  15.4150, 'lon' =>  -61.3710, 'zoom' => 11],
            ['code' => 'DO', 'name' => 'Dominican Republic',               'name_es' => 'República Dominicana',              'lat' =>  18.7357, 'lon' =>  -70.1627, 'zoom' =>  7],
            ['code' => 'DZ', 'name' => 'Algeria',                          'name_es' => 'Argelia',                           'lat' =>  28.0339, 'lon' =>    1.6596, 'zoom' =>  5],
            ['code' => 'EC', 'name' => 'Ecuador',                          'name_es' => 'Ecuador',                           'lat' =>  -1.8312, 'lon' =>  -78.1834, 'zoom' =>  6],
            ['code' => 'EE', 'name' => 'Estonia',                          'name_es' => 'Estonia',                           'lat' =>  58.5953, 'lon' =>   25.0136, 'zoom' =>  7],
            ['code' => 'EG', 'name' => 'Egypt',                            'name_es' => 'Egipto',                            'lat' =>  26.8206, 'lon' =>   30.8025, 'zoom' =>  5],
            ['code' => 'ER', 'name' => 'Eritrea',                          'name_es' => 'Eritrea',                           'lat' =>  15.1794, 'lon' =>   39.7823, 'zoom' =>  7],
            ['code' => 'ES', 'name' => 'Spain',                            'name_es' => 'España',                            'lat' =>  40.4637, 'lon' =>   -3.7492, 'zoom' =>  5],
            ['code' => 'ET', 'name' => 'Ethiopia',                         'name_es' => 'Etiopía',                           'lat' =>   9.1450, 'lon' =>   40.4897, 'zoom' =>  5],
            ['code' => 'FI', 'name' => 'Finland',                          'name_es' => 'Finlandia',                         'lat' =>  61.9241, 'lon' =>   25.7482, 'zoom' =>  5],
            ['code' => 'FJ', 'name' => 'Fiji',                             'name_es' => 'Fiyi',                              'lat' => -16.5782, 'lon' =>  179.4144, 'zoom' =>  8],
            ['code' => 'FM', 'name' => 'Micronesia',                       'name_es' => 'Micronesia',                        'lat' =>   7.4256, 'lon' =>  150.5508, 'zoom' =>  6],
            ['code' => 'FR', 'name' => 'France',                           'name_es' => 'Francia',                           'lat' =>  46.2276, 'lon' =>    2.2137, 'zoom' =>  5],
            ['code' => 'GA', 'name' => 'Gabon',                            'name_es' => 'Gabón',                             'lat' =>  -0.8037, 'lon' =>   11.6094, 'zoom' =>  6],
            ['code' => 'GB', 'name' => 'United Kingdom',                   'name_es' => 'Reino Unido',                       'lat' =>  55.3781, 'lon' =>   -3.4360, 'zoom' =>  5],
            ['code' => 'GD', 'name' => 'Grenada',                          'name_es' => 'Granada',                           'lat' =>  12.1165, 'lon' =>  -61.6790, 'zoom' => 11],
            ['code' => 'GE', 'name' => 'Georgia',                          'name_es' => 'Georgia',                           'lat' =>  42.3154, 'lon' =>   43.3569, 'zoom' =>  7],
            ['code' => 'GH', 'name' => 'Ghana',                            'name_es' => 'Ghana',                             'lat' =>   7.9465, 'lon' =>   -1.0232, 'zoom' =>  6],
            ['code' => 'GM', 'name' => 'Gambia',                           'name_es' => 'Gambia',                            'lat' =>  13.4432, 'lon' =>  -15.3101, 'zoom' =>  8],
            ['code' => 'GN', 'name' => 'Guinea',                           'name_es' => 'Guinea',                            'lat' =>   9.9456, 'lon' =>  -11.2878, 'zoom' =>  7],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea',                'name_es' => 'Guinea Ecuatorial',                 'lat' =>   1.6508, 'lon' =>   10.2679, 'zoom' =>  8],
            ['code' => 'GR', 'name' => 'Greece',                           'name_es' => 'Grecia',                            'lat' =>  39.0742, 'lon' =>   21.8243, 'zoom' =>  6],
            ['code' => 'GT', 'name' => 'Guatemala',                        'name_es' => 'Guatemala',                         'lat' =>  15.7835, 'lon' =>  -90.2308, 'zoom' =>  7],
            ['code' => 'GW', 'name' => 'Guinea-Bissau',                    'name_es' => 'Guinea-Bisáu',                      'lat' =>  11.8037, 'lon' =>  -15.1804, 'zoom' =>  8],
            ['code' => 'GY', 'name' => 'Guyana',                           'name_es' => 'Guyana',                            'lat' =>   4.8604, 'lon' =>  -58.9302, 'zoom' =>  6],
            ['code' => 'HN', 'name' => 'Honduras',                         'name_es' => 'Honduras',                         'lat' =>  15.2000, 'lon' =>  -86.2419, 'zoom' =>  7],
            ['code' => 'HR', 'name' => 'Croatia',                          'name_es' => 'Croacia',                           'lat' =>  45.1000, 'lon' =>   15.2000, 'zoom' =>  7],
            ['code' => 'HT', 'name' => 'Haiti',                            'name_es' => 'Haití',                             'lat' =>  18.9712, 'lon' =>  -72.2852, 'zoom' =>  8],
            ['code' => 'HU', 'name' => 'Hungary',                          'name_es' => 'Hungría',                           'lat' =>  47.1625, 'lon' =>   19.5033, 'zoom' =>  7],
            ['code' => 'ID', 'name' => 'Indonesia',                        'name_es' => 'Indonesia',                         'lat' =>  -0.7893, 'lon' =>  113.9213, 'zoom' =>  4],
            ['code' => 'IE', 'name' => 'Ireland',                          'name_es' => 'Irlanda',                           'lat' =>  53.4129, 'lon' =>   -8.2439, 'zoom' =>  7],
            ['code' => 'IL', 'name' => 'Israel',                           'name_es' => 'Israel',                            'lat' =>  31.0461, 'lon' =>   34.8516, 'zoom' =>  7],
            ['code' => 'IN', 'name' => 'India',                            'name_es' => 'India',                             'lat' =>  20.5937, 'lon' =>   78.9629, 'zoom' =>  4],
            ['code' => 'IQ', 'name' => 'Iraq',                             'name_es' => 'Irak',                              'lat' =>  33.2232, 'lon' =>   43.6793, 'zoom' =>  6],
            ['code' => 'IR', 'name' => 'Iran',                             'name_es' => 'Irán',                              'lat' =>  32.4279, 'lon' =>   53.6880, 'zoom' =>  5],
            ['code' => 'IS', 'name' => 'Iceland',                          'name_es' => 'Islandia',                          'lat' =>  64.9631, 'lon' =>  -19.0208, 'zoom' =>  6],
            ['code' => 'IT', 'name' => 'Italy',                            'name_es' => 'Italia',                            'lat' =>  41.8719, 'lon' =>   12.5674, 'zoom' =>  5],
            ['code' => 'JM', 'name' => 'Jamaica',                          'name_es' => 'Jamaica',                           'lat' =>  18.1096, 'lon' =>  -77.2975, 'zoom' =>  8],
            ['code' => 'JO', 'name' => 'Jordan',                           'name_es' => 'Jordania',                          'lat' =>  30.5852, 'lon' =>   36.2384, 'zoom' =>  7],
            ['code' => 'JP', 'name' => 'Japan',                            'name_es' => 'Japón',                             'lat' =>  36.2048, 'lon' =>  138.2529, 'zoom' =>  5],
            ['code' => 'KE', 'name' => 'Kenya',                            'name_es' => 'Kenia',                             'lat' =>  -0.0236, 'lon' =>   37.9062, 'zoom' =>  6],
            ['code' => 'KG', 'name' => 'Kyrgyzstan',                       'name_es' => 'Kirguistán',                        'lat' =>  41.2044, 'lon' =>   74.7661, 'zoom' =>  6],
            ['code' => 'KH', 'name' => 'Cambodia',                         'name_es' => 'Camboya',                           'lat' =>  12.5657, 'lon' =>  104.9910, 'zoom' =>  7],
            ['code' => 'KI', 'name' => 'Kiribati',                         'name_es' => 'Kiribati',                          'lat' =>  -3.3704, 'lon' => -168.7340, 'zoom' =>  4],
            ['code' => 'KM', 'name' => 'Comoros',                          'name_es' => 'Comoras',                           'lat' => -11.6455, 'lon' =>   43.3333, 'zoom' =>  9],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis',            'name_es' => 'San Cristóbal y Nieves',            'lat' =>  17.3578, 'lon' =>  -62.7830, 'zoom' => 11],
            ['code' => 'KP', 'name' => 'North Korea',                      'name_es' => 'Corea del Norte',                   'lat' =>  40.3399, 'lon' =>  127.5101, 'zoom' =>  6],
            ['code' => 'KR', 'name' => 'South Korea',                      'name_es' => 'Corea del Sur',                     'lat' =>  35.9078, 'lon' =>  127.7669, 'zoom' =>  6],
            ['code' => 'KW', 'name' => 'Kuwait',                           'name_es' => 'Kuwait',                            'lat' =>  29.3117, 'lon' =>   47.4818, 'zoom' =>  8],
            ['code' => 'KZ', 'name' => 'Kazakhstan',                       'name_es' => 'Kazajistán',                        'lat' =>  48.0196, 'lon' =>   66.9237, 'zoom' =>  4],
            ['code' => 'LA', 'name' => 'Laos',                             'name_es' => 'Laos',                              'lat' =>  19.8563, 'lon' =>  102.4955, 'zoom' =>  6],
            ['code' => 'LB', 'name' => 'Lebanon',                          'name_es' => 'Líbano',                            'lat' =>  33.8547, 'lon' =>   35.8623, 'zoom' =>  8],
            ['code' => 'LC', 'name' => 'Saint Lucia',                      'name_es' => 'Santa Lucía',                       'lat' =>  13.9094, 'lon' =>  -60.9789, 'zoom' => 11],
            ['code' => 'LI', 'name' => 'Liechtenstein',                    'name_es' => 'Liechtenstein',                     'lat' =>  47.1660, 'lon' =>    9.5554, 'zoom' => 11],
            ['code' => 'LK', 'name' => 'Sri Lanka',                        'name_es' => 'Sri Lanka',                         'lat' =>   7.8731, 'lon' =>   80.7718, 'zoom' =>  7],
            ['code' => 'LR', 'name' => 'Liberia',                          'name_es' => 'Liberia',                           'lat' =>   6.4281, 'lon' =>   -9.4295, 'zoom' =>  7],
            ['code' => 'LS', 'name' => 'Lesotho',                          'name_es' => 'Lesoto',                            'lat' => -29.6100, 'lon' =>   28.2336, 'zoom' =>  8],
            ['code' => 'LT', 'name' => 'Lithuania',                        'name_es' => 'Lituania',                          'lat' =>  55.1694, 'lon' =>   23.8813, 'zoom' =>  7],
            ['code' => 'LU', 'name' => 'Luxembourg',                       'name_es' => 'Luxemburgo',                        'lat' =>  49.8153, 'lon' =>    6.1296, 'zoom' =>  9],
            ['code' => 'LV', 'name' => 'Latvia',                           'name_es' => 'Letonia',                           'lat' =>  56.8796, 'lon' =>   24.6032, 'zoom' =>  7],
            ['code' => 'LY', 'name' => 'Libya',                            'name_es' => 'Libia',                             'lat' =>  26.3351, 'lon' =>   17.2283, 'zoom' =>  5],
            ['code' => 'MA', 'name' => 'Morocco',                          'name_es' => 'Marruecos',                         'lat' =>  31.7917, 'lon' =>   -7.0926, 'zoom' =>  5],
            ['code' => 'MC', 'name' => 'Monaco',                           'name_es' => 'Mónaco',                            'lat' =>  43.7384, 'lon' =>    7.4246, 'zoom' => 13],
            ['code' => 'MD', 'name' => 'Moldova',                          'name_es' => 'Moldavia',                          'lat' =>  47.4116, 'lon' =>   28.3699, 'zoom' =>  7],
            ['code' => 'ME', 'name' => 'Montenegro',                       'name_es' => 'Montenegro',                        'lat' =>  42.7087, 'lon' =>   19.3744, 'zoom' =>  8],
            ['code' => 'MG', 'name' => 'Madagascar',                       'name_es' => 'Madagascar',                        'lat' => -18.7669, 'lon' =>   46.8691, 'zoom' =>  5],
            ['code' => 'MH', 'name' => 'Marshall Islands',                 'name_es' => 'Islas Marshall',                    'lat' =>   7.1315, 'lon' =>  171.1845, 'zoom' =>  7],
            ['code' => 'MK', 'name' => 'North Macedonia',                  'name_es' => 'Macedonia del Norte',               'lat' =>  41.6086, 'lon' =>   21.7453, 'zoom' =>  8],
            ['code' => 'ML', 'name' => 'Mali',                             'name_es' => 'Mali',                              'lat' =>  17.5707, 'lon' =>   -3.9962, 'zoom' =>  5],
            ['code' => 'MM', 'name' => 'Myanmar',                          'name_es' => 'Myanmar',                           'lat' =>  21.9162, 'lon' =>   95.9560, 'zoom' =>  5],
            ['code' => 'MN', 'name' => 'Mongolia',                         'name_es' => 'Mongolia',                          'lat' =>  46.8625, 'lon' =>  103.8467, 'zoom' =>  4],
            ['code' => 'MR', 'name' => 'Mauritania',                       'name_es' => 'Mauritania',                        'lat' =>  21.0079, 'lon' =>  -10.9408, 'zoom' =>  5],
            ['code' => 'MT', 'name' => 'Malta',                            'name_es' => 'Malta',                             'lat' =>  35.9375, 'lon' =>   14.3754, 'zoom' => 10],
            ['code' => 'MU', 'name' => 'Mauritius',                        'name_es' => 'Mauricio',                          'lat' => -20.3484, 'lon' =>   57.5522, 'zoom' =>  9],
            ['code' => 'MV', 'name' => 'Maldives',                         'name_es' => 'Maldivas',                          'lat' =>   3.2028, 'lon' =>   73.2207, 'zoom' =>  7],
            ['code' => 'MW', 'name' => 'Malawi',                           'name_es' => 'Malaui',                            'lat' => -13.2543, 'lon' =>   34.3015, 'zoom' =>  6],
            ['code' => 'MX', 'name' => 'Mexico',                           'name_es' => 'México',                            'lat' =>  23.6345, 'lon' => -102.5528, 'zoom' =>  4],
            ['code' => 'MY', 'name' => 'Malaysia',                         'name_es' => 'Malasia',                           'lat' =>   4.2105, 'lon' =>  101.9758, 'zoom' =>  5],
            ['code' => 'MZ', 'name' => 'Mozambique',                       'name_es' => 'Mozambique',                        'lat' => -18.6657, 'lon' =>   35.5296, 'zoom' =>  5],
            ['code' => 'NA', 'name' => 'Namibia',                          'name_es' => 'Namibia',                           'lat' => -22.9576, 'lon' =>   18.4904, 'zoom' =>  5],
            ['code' => 'NE', 'name' => 'Niger',                            'name_es' => 'Níger',                             'lat' =>  17.6078, 'lon' =>    8.0817, 'zoom' =>  5],
            ['code' => 'NG', 'name' => 'Nigeria',                          'name_es' => 'Nigeria',                           'lat' =>   9.0820, 'lon' =>    8.6753, 'zoom' =>  5],
            ['code' => 'NI', 'name' => 'Nicaragua',                        'name_es' => 'Nicaragua',                         'lat' =>  12.8654, 'lon' =>  -85.2072, 'zoom' =>  7],
            ['code' => 'NL', 'name' => 'Netherlands',                      'name_es' => 'Países Bajos',                      'lat' =>  52.1326, 'lon' =>    5.2913, 'zoom' =>  7],
            ['code' => 'NO', 'name' => 'Norway',                           'name_es' => 'Noruega',                           'lat' =>  60.4720, 'lon' =>    8.4689, 'zoom' =>  5],
            ['code' => 'NP', 'name' => 'Nepal',                            'name_es' => 'Nepal',                             'lat' =>  28.3949, 'lon' =>   84.1240, 'zoom' =>  6],
            ['code' => 'NR', 'name' => 'Nauru',                            'name_es' => 'Nauru',                             'lat' =>  -0.5228, 'lon' =>  166.9315, 'zoom' => 13],
            ['code' => 'NZ', 'name' => 'New Zealand',                      'name_es' => 'Nueva Zelanda',                     'lat' => -40.9006, 'lon' =>  174.8860, 'zoom' =>  5],
            ['code' => 'OM', 'name' => 'Oman',                             'name_es' => 'Omán',                              'lat' =>  21.4735, 'lon' =>   55.9754, 'zoom' =>  6],
            ['code' => 'PA', 'name' => 'Panama',                           'name_es' => 'Panamá',                            'lat' =>   8.5380, 'lon' =>  -80.7821, 'zoom' =>  7],
            ['code' => 'PE', 'name' => 'Peru',                             'name_es' => 'Perú',                              'lat' =>  -9.1900, 'lon' =>  -75.0152, 'zoom' =>  5],
            ['code' => 'PG', 'name' => 'Papua New Guinea',                 'name_es' => 'Papúa Nueva Guinea',                'lat' =>  -6.3149, 'lon' =>  143.9555, 'zoom' =>  5],
            ['code' => 'PH', 'name' => 'Philippines',                      'name_es' => 'Filipinas',                         'lat' =>  12.8797, 'lon' =>  121.7740, 'zoom' =>  5],
            ['code' => 'PK', 'name' => 'Pakistan',                         'name_es' => 'Pakistán',                          'lat' =>  30.3753, 'lon' =>   69.3451, 'zoom' =>  5],
            ['code' => 'PL', 'name' => 'Poland',                           'name_es' => 'Polonia',                           'lat' =>  51.9194, 'lon' =>   19.1451, 'zoom' =>  6],
            ['code' => 'PS', 'name' => 'Palestine',                        'name_es' => 'Palestina',                         'lat' =>  31.9522, 'lon' =>   35.2332, 'zoom' =>  8],
            ['code' => 'PT', 'name' => 'Portugal',                         'name_es' => 'Portugal',                          'lat' =>  39.3999, 'lon' =>   -8.2245, 'zoom' =>  6],
            ['code' => 'PW', 'name' => 'Palau',                            'name_es' => 'Palaos',                            'lat' =>   7.5150, 'lon' =>  134.5825, 'zoom' =>  9],
            ['code' => 'PY', 'name' => 'Paraguay',                         'name_es' => 'Paraguay',                          'lat' => -23.4425, 'lon' =>  -58.4438, 'zoom' =>  6],
            ['code' => 'QA', 'name' => 'Qatar',                            'name_es' => 'Catar',                             'lat' =>  25.3548, 'lon' =>   51.1839, 'zoom' =>  8],
            ['code' => 'RO', 'name' => 'Romania',                          'name_es' => 'Rumanía',                           'lat' =>  45.9432, 'lon' =>   24.9668, 'zoom' =>  6],
            ['code' => 'RS', 'name' => 'Serbia',                           'name_es' => 'Serbia',                            'lat' =>  44.0165, 'lon' =>   21.0059, 'zoom' =>  7],
            ['code' => 'RU', 'name' => 'Russia',                           'name_es' => 'Rusia',                             'lat' =>  61.5240, 'lon' =>  105.3188, 'zoom' =>  3],
            ['code' => 'RW', 'name' => 'Rwanda',                           'name_es' => 'Ruanda',                            'lat' =>  -1.9403, 'lon' =>   29.8739, 'zoom' =>  8],
            ['code' => 'SA', 'name' => 'Saudi Arabia',                     'name_es' => 'Arabia Saudita',                    'lat' =>  23.8859, 'lon' =>   45.0792, 'zoom' =>  5],
            ['code' => 'SB', 'name' => 'Solomon Islands',                  'name_es' => 'Islas Salomón',                     'lat' =>  -9.6457, 'lon' =>  160.1562, 'zoom' =>  7],
            ['code' => 'SC', 'name' => 'Seychelles',                       'name_es' => 'Seychelles',                        'lat' =>  -4.6796, 'lon' =>   55.4920, 'zoom' =>  9],
            ['code' => 'SD', 'name' => 'Sudan',                            'name_es' => 'Sudán',                             'lat' =>  12.8628, 'lon' =>   30.2176, 'zoom' =>  5],
            ['code' => 'SE', 'name' => 'Sweden',                           'name_es' => 'Suecia',                            'lat' =>  60.1282, 'lon' =>   18.6435, 'zoom' =>  5],
            ['code' => 'SG', 'name' => 'Singapore',                        'name_es' => 'Singapur',                          'lat' =>   1.3521, 'lon' =>  103.8198, 'zoom' => 11],
            ['code' => 'SI', 'name' => 'Slovenia',                         'name_es' => 'Eslovenia',                         'lat' =>  46.1512, 'lon' =>   14.9955, 'zoom' =>  8],
            ['code' => 'SK', 'name' => 'Slovakia',                         'name_es' => 'Eslovaquia',                        'lat' =>  48.6690, 'lon' =>   19.6990, 'zoom' =>  7],
            ['code' => 'SL', 'name' => 'Sierra Leone',                     'name_es' => 'Sierra Leona',                      'lat' =>   8.4606, 'lon' =>  -11.7799, 'zoom' =>  7],
            ['code' => 'SM', 'name' => 'San Marino',                       'name_es' => 'San Marino',                        'lat' =>  43.9424, 'lon' =>   12.4578, 'zoom' => 12],
            ['code' => 'SN', 'name' => 'Senegal',                          'name_es' => 'Senegal',                           'lat' =>  14.4974, 'lon' =>  -14.4524, 'zoom' =>  6],
            ['code' => 'SO', 'name' => 'Somalia',                          'name_es' => 'Somalia',                           'lat' =>   5.1521, 'lon' =>   46.1996, 'zoom' =>  5],
            ['code' => 'SR', 'name' => 'Suriname',                         'name_es' => 'Surinam',                           'lat' =>   3.9193, 'lon' =>  -56.0278, 'zoom' =>  6],
            ['code' => 'SS', 'name' => 'South Sudan',                      'name_es' => 'Sudán del Sur',                     'lat' =>   6.8770, 'lon' =>   31.3070, 'zoom' =>  6],
            ['code' => 'ST', 'name' => 'São Tomé and Príncipe',           'name_es' => 'Santo Tomé y Príncipe',             'lat' =>   0.1864, 'lon' =>    6.6131, 'zoom' =>  9],
            ['code' => 'SV', 'name' => 'El Salvador',                      'name_es' => 'El Salvador',                       'lat' =>  13.7942, 'lon' =>  -88.8965, 'zoom' =>  8],
            ['code' => 'SY', 'name' => 'Syria',                            'name_es' => 'Siria',                             'lat' =>  34.8021, 'lon' =>   38.9968, 'zoom' =>  6],
            ['code' => 'SZ', 'name' => 'Eswatini',                         'name_es' => 'Esuatini',                          'lat' => -26.5225, 'lon' =>   31.4659, 'zoom' =>  9],
            ['code' => 'TD', 'name' => 'Chad',                             'name_es' => 'Chad',                              'lat' =>  15.4542, 'lon' =>   18.7322, 'zoom' =>  5],
            ['code' => 'TG', 'name' => 'Togo',                             'name_es' => 'Togo',                              'lat' =>   8.6195, 'lon' =>    0.8248, 'zoom' =>  7],
            ['code' => 'TH', 'name' => 'Thailand',                         'name_es' => 'Tailandia',                         'lat' =>  15.8700, 'lon' =>  100.9925, 'zoom' =>  5],
            ['code' => 'TJ', 'name' => 'Tajikistan',                       'name_es' => 'Tayikistán',                        'lat' =>  38.8610, 'lon' =>   71.2761, 'zoom' =>  6],
            ['code' => 'TL', 'name' => 'Timor-Leste',                      'name_es' => 'Timor Oriental',                    'lat' =>  -8.8742, 'lon' =>  125.7275, 'zoom' =>  8],
            ['code' => 'TM', 'name' => 'Turkmenistan',                     'name_es' => 'Turkmenistán',                      'lat' =>  38.9697, 'lon' =>   59.5563, 'zoom' =>  5],
            ['code' => 'TN', 'name' => 'Tunisia',                          'name_es' => 'Túnez',                             'lat' =>  33.8869, 'lon' =>    9.5375, 'zoom' =>  6],
            ['code' => 'TO', 'name' => 'Tonga',                            'name_es' => 'Tonga',                             'lat' => -21.1790, 'lon' => -175.1982, 'zoom' =>  9],
            ['code' => 'TR', 'name' => 'Turkey',                           'name_es' => 'Turquía',                           'lat' =>  38.9637, 'lon' =>   35.2433, 'zoom' =>  5],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago',              'name_es' => 'Trinidad y Tobago',                 'lat' =>  10.6918, 'lon' =>  -61.2225, 'zoom' =>  9],
            ['code' => 'TV', 'name' => 'Tuvalu',                           'name_es' => 'Tuvalu',                            'lat' =>  -7.1095, 'lon' =>  177.6493, 'zoom' => 12],
            ['code' => 'TZ', 'name' => 'Tanzania',                         'name_es' => 'Tanzania',                          'lat' =>  -6.3690, 'lon' =>   34.8888, 'zoom' =>  5],
            ['code' => 'UA', 'name' => 'Ukraine',                          'name_es' => 'Ucrania',                           'lat' =>  48.3794, 'lon' =>   31.1656, 'zoom' =>  5],
            ['code' => 'UG', 'name' => 'Uganda',                           'name_es' => 'Uganda',                            'lat' =>   1.3733, 'lon' =>   32.2903, 'zoom' =>  7],
            ['code' => 'US', 'name' => 'United States',                    'name_es' => 'Estados Unidos',                    'lat' =>  37.0902, 'lon' =>  -95.7129, 'zoom' =>  4],
            ['code' => 'UY', 'name' => 'Uruguay',                          'name_es' => 'Uruguay',                           'lat' => -32.5228, 'lon' =>  -55.7658, 'zoom' =>  6],
            ['code' => 'UZ', 'name' => 'Uzbekistan',                       'name_es' => 'Uzbekistán',                        'lat' =>  41.3775, 'lon' =>   64.5853, 'zoom' =>  5],
            ['code' => 'VA', 'name' => 'Vatican City',                     'name_es' => 'Ciudad del Vaticano',               'lat' =>  41.9029, 'lon' =>   12.4534, 'zoom' => 14],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'name_es' => 'San Vicente y las Granadinas',      'lat' =>  12.9843, 'lon' =>  -61.2872, 'zoom' => 11],
            ['code' => 'VE', 'name' => 'Venezuela',                        'name_es' => 'Venezuela',                         'lat' =>   6.4238, 'lon' =>  -66.5897, 'zoom' =>  5],
            ['code' => 'VN', 'name' => 'Vietnam',                          'name_es' => 'Vietnam',                           'lat' =>  14.0583, 'lon' =>  108.2772, 'zoom' =>  5],
            ['code' => 'VU', 'name' => 'Vanuatu',                          'name_es' => 'Vanuatu',                           'lat' => -15.3767, 'lon' =>  166.9592, 'zoom' =>  7],
            ['code' => 'WS', 'name' => 'Samoa',                            'name_es' => 'Samoa',                             'lat' => -13.7590, 'lon' => -172.1046, 'zoom' =>  9],
            ['code' => 'XK', 'name' => 'Kosovo',                           'name_es' => 'Kosovo',                            'lat' =>  42.6026, 'lon' =>   20.9030, 'zoom' =>  8],
            ['code' => 'YE', 'name' => 'Yemen',                            'name_es' => 'Yemen',                             'lat' =>  15.5527, 'lon' =>   48.5164, 'zoom' =>  6],
            ['code' => 'ZA', 'name' => 'South Africa',                     'name_es' => 'Sudáfrica',                         'lat' => -30.5595, 'lon' =>   22.9375, 'zoom' =>  5],
            ['code' => 'ZM', 'name' => 'Zambia',                           'name_es' => 'Zambia',                            'lat' => -13.1339, 'lon' =>   27.8493, 'zoom' =>  6],
            ['code' => 'ZW', 'name' => 'Zimbabwe',                         'name_es' => 'Zimbabue',                          'lat' => -19.0154, 'lon' =>   29.1549, 'zoom' =>  6],
        ];

        foreach ($countries as $c) {
            Country::firstOrCreate(
                ['code' => $c['code']],
                [
                    'name'         => $c['name'],
                    'name_es'      => $c['name_es'],
                    'slug'         => Str::slug($c['name']),
                    'flag_emoji'   => $this->flag($c['code']),
                    'latitude'     => $c['lat'],
                    'longitude'    => $c['lon'],
                    'default_zoom' => $c['zoom'],
                ]
            );
        }

        $this->command->info('AllCountriesSeeder: ' . count($countries) . ' countries seeded.');
    }

    /**
     * Build a flag emoji from a 2-letter ISO country code.
     * Each letter maps to a Unicode Regional Indicator Symbol (U+1F1E6–U+1F1FF).
     */
    private function flag(string $code): string
    {
        $offset = 0x1F1E6 - ord('A');
        return implode('', array_map(
            fn(string $ch) => mb_chr($offset + ord($ch), 'UTF-8'),
            str_split(strtoupper($code))
        ));
    }
}
